pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - chmod +x gradlew
      - ./gradlew build --console plain
  release:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - build/lib/*.jar
    when:
      event: tag
